# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-config
#   namespace: cicd
# data:
#   db_name: drone
#   user: drone
  # delete root_pass and user_pass once mysql-secret is working properly
  # root_pass: rootpass
  # user_pass: dronepass
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cicd
  labels:
    app: mysql
    service: database
  annotations:
    'prometheus.io/scrape': 'true'
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
    service: database
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: cicd
  labels:
    app: mysql
    service: database
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        service: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        args:
        - mysqld
        - --bind-address=0.0.0.0
        ports:
        - name: http
          containerPort: 3306
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: root_pass
        # - name: MYSQL_DATABASE
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: db_name
        # - name: MYSQL_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: user
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: user_pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root_pass
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user_pass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_name
        resources:
          requests:
            cpu: "0.01"
        volumeMounts:
        - name: mysql-cicd-data
          mountPath: /var/lib/mysql
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: mysql-cicd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
